### ISSUE TITLE
Add support pt-BR

### ISSUE THREAD

**Issue by jniltinho** [gogits/gogsweb#7]
Add support pt-BR

Error

[Macaron] Started GET /docs/middlewares/gzip/?lang=pt-BR for 127.0.0.1
[Macaron] Completed /docs/middlewares/gzip/?lang=pt-BR 302 Found in 167.549µs
[Macaron] Started GET /docs/middlewares/gzip/ for 127.0.0.1
[Macaron] Completed /docs/middlewares/gzip/ 404 Not Found in 130.953µs
[Macaron] Started GET /docs/middlewares/gzip.html for 127.0.0.1
[Macaron] Completed /docs/middlewares/gzip.html 404 Not Found in 182.704µs
[Macaron] Started GET /docs/middlewares/gzip.html for 127.0.0.1
[Macaron] Completed /docs/middlewares/gzip.html 404 Not Found in 141.289µs
[Macaron] Started GET /docs/middlewares/gzip.html for 127.0.0.1
[Macaron] Completed /docs/middlewares/gzip.html 404 Not Found in 111.327µs

https://github.com/renatosuero/macaron-docs

**Comment by Unknwon** [comment]
Hi, thanks your contribution!

In order to add another language, the [config option](https://github.com/gogits/gogsweb/blob/master/conf/app.ini#L11-L12) must be updated as well.

Hope helps!
